### ISSUE TITLE
Miiko quotes

### ISSUE THREAD

**Issue by InoxydableWrite** [NatoBoram/Go-Miiko#1]
Suggestions de mots / phrases auxquelles elle devait réagir, avec des suggestions de réponses (J'en ai pas mis énormément, tu peux en ajouter) de sa part (J'inclus pas les fautes que les gens pourraient faire, mais il faudrait en mettre, genre écrire Miko au lieu de Miiko par exemple) :
______________________________________________________

"Miiko" (faible taux de réponse, pt'être genre 30%)

Réponses:
"Oui?"
"On parle de moi?"
"Coucou!"
"C'est bien moi!"
"Je peux m'inscruster?"
______________________________________________________

"Miiko?" "Miiko!" "Salut Miiko" "Coucou Miiko" etc. (et autres dans le genre? genre on l'interpelle exprès) (Taux de réponse assez élevé, genre 70% voir plus)

Réponses:

"Coucou!"
"Bonjour les gens"
"Ah! Vous ne voyez donc pas que je suis occupée!"
"Oh, désolée, je faisais autre chose..."
"Bonjour!"
"Oui?"
"Je suis là!"
"Qu'est-ce qui se passe?"
______________________________________________________

"Friandises", "Friandise", "Bonbon", "Chocolat"(Et autres bonbons quelquonques) (Taux aussi élevé que "popcorn")

Réponses:

"J'adore les friandises!"
"Vous avez des friandises?!? J'EN VEUX!!"
"Des friandises? Où ça?"
"J'adore le chocolat! Oh, et les jujubes! Et les sucettes! et..."
"Hmmmmmm....... friandiiiiiiiiiises......"
"Des friandises!!!"
"Parlant de friandises, quelqu'un en aurait à me donner?"
"Ooooh vous parlez de friandises!"
"*munch munch* Oh ch'est drôle que vous parlchiez de friandiches, je mancheais chustement un peu che chocolat"
______________________________________________________

"*patpat Miiko*" "patpat Miiko" (et autres) (Taux de 100%)

Réponses:

":patpat:"
"._."
"De que?"
"*patpat*"
"*patpat [personne qui a écrit le message]*"
______________________________________________________

SI ERME écrit n'importe quel message contenant le mot "Miiko", elle a un fort taux de chance (voir 100%? Quoi que c'est peut-être un peu too much) de lui répondre:

"Ermeeeeeeeee!"
"Ermelinde :3"
"Mon Erme d'amour!"
"Ermelinde <3"
"Coucou Erme :3"
"Erme parle de moi! *-*"
"Ça va Erme? :smirk:"
"*Saute au cou d'Erme*"
"Moi aussi je t'aime, Erme!"
"Mon petit Ermelinde d'amour que j'aime *-*"
"Je t'aime, Ermelinde!"
______________________________________________________
Commande pour voir le nombre de gens dans les gardes OU phrases du genre "Combien sommes-nous dans la garde Absynthe?", mais ça risque d'être long donc une commande serait peut-être mieux (Comme pour purger)

Réponse:

"Il y a présentement X membres dans la garde Absynthe, X membres dans la garde de l'Ombre et X membres dans la garde Obsidienne."
"Nous comptons pour l'instant X membres dans la garde Absynthe, X membres dans la garde de l'Ombre et X membres dans la garde Obsidienne."
"Il y a présentement X membres dans la garde X."
Et autres variantes.

**Comment by NatoBoram** [comment]
Il faudrait séparer l'issue en plusieurs morceaux. Sans ça, ça va être difficile à développer et indiquer où je suis rendu.

* Parler de Miiko
* Interpeller Miiko
* Friandises
* Bonbons
* Chocolat
* Patpat
* Chouchou

**Comment by NatoBoram** [comment]
Les issues ont été ajoutés.
